### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libkompute-jni.so" not found

### ISSUE THREAD

**Issue by PascalPolygon** [EthicalML/vulkan-kompute#125]
Hello, I am following the following tutorial: https://towardsdatascience.com/gpu-accelerated-machine-learning-in-your-mobile-applications-using-the-android-ndk-vulkan-kompute-1e9da37b7617. I am running ubuntu 20 and whenever I run the emulator I get the following error.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ethicalml.kompute, PID: 14488
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libkompute-jni.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.ethicalml.kompute.KomputeJni.<clinit>(KomputeJni.kt:80)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process: Sending signal. PID: 14488 SIG: 9
`

**Comment by axsaucedo** [comment]
This could be many reasons but the most probably would be due to the emulator not supporting Vulkan, which phone are you emulating this on?

**Comment by PascalPolygon** [comment]
Pixel 2 w API 30. That's the same you used in the tutorial right?

**Comment by axsaucedo** [comment]
Hmm strange - a couple of questions:
* do you have the Vulkan SDK installed? 
* could you try with a different emulator like Pixel XL? 
* Are you trying to run the example exactly as provided (in the repo under `examples/android`) or with differences?

**Comment by PascalPolygon** [comment]
Thanks for the responses.
Is there a specific installation step for the Vulkan SDK? I assumed that cloning and running the demo as is would have all the dependencies. I am trying to run it as is.

**Comment by axsaucedo** [comment]
I am looking at the documentation in the Android NDK and strangely I can't really see an explicit step where it requires installing the Vulkan SDK. I assumed that it would be a requirement as it comes will all the relevant libraries, but it may be the case that in the emulator the Vulkan interface is actually abstracted / mocked as well (although from the error you are getting it clearly does need the library). I can't really tell, but I would suggest those steps above initially, namely testing with that emulator, and if not installing the SDK. The installation of the Vulkan SDK is quite straightforward, it can be found in the official website https://vulkan.lunarg.com/

**Comment by axsaucedo** [comment]
@PascalPolygon did this get resolved?

**Comment by axsaucedo** [comment]
Closing for inactivity, reopen if still an issue with latest version

**Comment by mariaRoxana94** [comment]
Hello! I had the same issue as above. Can someone tell me what was the solution? Thxin advance!

**Comment by axsaucedo** [comment]
It seems the JNI is not properly building for you, do you see any erros on the CMAKE?

**Comment by mariaRoxana94** [comment]
I opened from vulkan-compute just the android-simple with android studio, not the whole project vulkan-compute.
The only errors are these, at the build in the Sync tab:
 
![Android](https://user-images.githubusercontent.com/36856028/123148123-87810900-d468-11eb-8cf9-2e0ef4140081.png)

**Comment by axsaucedo** [comment]
Just gave it a try and couldn't see any issues, updated to the latest android studio as well. I don't think there was any particualr configuration - there is quite a lot of options on the IDE, so would be a bit of an exploration to get it running, but can confirm it's working:

![image](https://user-images.githubusercontent.com/1447507/123169273-f95d5080-d470-11eb-8309-ca91e0feadd0.png)
